name: weather_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ustaw kompatybilną wersję SDK Dart

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0 # Do obsługi zapytań HTTP
  flutter_dotenv: ^5.0.2 # Do obsługi pliku .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ # Folder na zasoby, np. zdjęcia ikon pogody
    - .env
